apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttsh-backend-deployment
  labels:
    app: ttsh-backend
spec:
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels: 
      app: ttsh-backend
  template:
    metadata: 
      labels:
        app: ttsh-backend
    spec: 
      containers:
      - name: ttsh-backend
        image: ttshcontainerregistry.azurecr.io/ttsh-backend-image:v4
        ports:
        - containerPort: 3000
        envFrom:
          - configMapRef:
              name: ttsh-config-map
          - secretRef:
              name: ttsh-secret
---
apiVersion: v1
kind: Service
metadata:
  name: ttsh-backend-service
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: ttsh-backend
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ttsh-config-map
data:
  ENDPOINT: https://api.cognitive.microsofttranslator.com/
  LOCATION: global
  CUR_KEY: "0"
  NUM_STANDARD_KEYS: "2"