apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttsh-backend-deployment
  labels:
    app: ttsh-backend
spec:
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels: 
      app: ttsh-backend
  template:
    metadata: 
      labels:
        app: ttsh-backend
    spec: 
      containers:
      - name: ttsh-backend
        image: ttshcontainerregistry.azurecr.io/ttsh-backend-image:v3
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ttsh-backend-service
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: ttsh-backend